CREATE TABLE "brand_assets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"short_name" text,
	"league" text,
	"image_url" text,
	"image_kind" text,
	"image_width" integer,
	"image_height" integer,
	"primary_color" text,
	"secondary_color" text,
	"source" text NOT NULL,
	"rights" text DEFAULT 'unreviewed' NOT NULL,
	"attribution" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "brand_assets_kind_ck" CHECK ("brand_assets"."kind" in ('team','performer','production','venue','category')),
	CONSTRAINT "brand_assets_rights_ck" CHECK ("brand_assets"."rights" in ('provider_terms','licensed','unreviewed')),
	CONSTRAINT "brand_assets_image_https_ck" CHECK ("brand_assets"."image_url" is null or "brand_assets"."image_url" like 'https://%')
);
--> statement-breakpoint
CREATE UNIQUE INDEX "brand_assets_kind_key_uq" ON "brand_assets" USING btree ("kind","key");
--> statement-breakpoint
-- The main teams and shows to start with. Team logos are seeded 'unreviewed': they show in previews and never in a
-- sent email until staff set rights to 'licensed'. Colours and short names are used everywhere. Ticketmaster images
-- arrive through catalog sync, also 'unreviewed'. The concert default is our own artwork (public/email).
INSERT INTO "brand_assets" ("kind","key","name","short_name","league","image_url","image_kind","image_width","image_height","primary_color","secondary_color","source","rights","attribution") VALUES
('team','new-york-rangers','New York Rangers','NYR','NHL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nyr.png&h=160&w=160','logo',160,160,'#0038A8','#CE1126','seed','unreviewed',NULL),
('team','new-york-islanders','New York Islanders','NYI','NHL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nyi.png&h=160&w=160','logo',160,160,'#00539B','#F47D30','seed','unreviewed',NULL),
('team','new-jersey-devils','New Jersey Devils','NJD','NHL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nj.png&h=160&w=160','logo',160,160,'#CE1126','#000000','seed','unreviewed',NULL),
('team','boston-bruins','Boston Bruins','BOS','NHL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/bos.png&h=160&w=160','logo',160,160,'#000000','#FFB81C','seed','unreviewed',NULL),
('team','philadelphia-flyers','Philadelphia Flyers','PHI','NHL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/phi.png&h=160&w=160','logo',160,160,'#F74902','#000000','seed','unreviewed',NULL),
('team','detroit-red-wings','Detroit Red Wings','DET','NHL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/det.png&h=160&w=160','logo',160,160,'#CE1126','#FFFFFF','seed','unreviewed',NULL),
('team','toronto-maple-leafs','Toronto Maple Leafs','TOR','NHL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/tor.png&h=160&w=160','logo',160,160,'#00205B','#FFFFFF','seed','unreviewed',NULL),
('team','new-york-knicks','New York Knicks','NYK','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/ny.png&h=160&w=160','logo',160,160,'#006BB6','#F58426','seed','unreviewed',NULL),
('team','brooklyn-nets','Brooklyn Nets','BKN','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/bkn.png&h=160&w=160','logo',160,160,'#000000','#FFFFFF','seed','unreviewed',NULL),
('team','boston-celtics','Boston Celtics','BOS','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/bos.png&h=160&w=160','logo',160,160,'#007A33','#BA9653','seed','unreviewed',NULL),
('team','los-angeles-lakers','Los Angeles Lakers','LAL','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/lal.png&h=160&w=160','logo',160,160,'#552583','#FDB927','seed','unreviewed',NULL),
('team','golden-state-warriors','Golden State Warriors','GSW','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/gs.png&h=160&w=160','logo',160,160,'#1D428A','#FFC72C','seed','unreviewed',NULL),
('team','philadelphia-76ers','Philadelphia 76ers','PHI','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/phi.png&h=160&w=160','logo',160,160,'#006BB6','#ED174C','seed','unreviewed',NULL),
('team','chicago-bulls','Chicago Bulls','CHI','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/chi.png&h=160&w=160','logo',160,160,'#CE1141','#000000','seed','unreviewed',NULL),
('team','miami-heat','Miami Heat','MIA','NBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mia.png&h=160&w=160','logo',160,160,'#98002E','#F9A01B','seed','unreviewed',NULL),
('team','new-york-liberty','New York Liberty','NYL','WNBA','https://a.espncdn.com/combiner/i?img=/i/teamlogos/wnba/500/ny.png&h=160&w=160','logo',160,160,'#6ECEB2','#000000','seed','unreviewed',NULL),
('team','new-york-yankees','New York Yankees','NYY','MLB','https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nyy.png&h=160&w=160','logo',160,160,'#0C2340','#C4CED3','seed','unreviewed',NULL),
('team','new-york-mets','New York Mets','NYM','MLB','https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nym.png&h=160&w=160','logo',160,160,'#002D72','#FF5910','seed','unreviewed',NULL),
('team','boston-red-sox','Boston Red Sox','BOS','MLB','https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/bos.png&h=160&w=160','logo',160,160,'#BD3039','#0C2340','seed','unreviewed',NULL),
('team','los-angeles-dodgers','Los Angeles Dodgers','LAD','MLB','https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/lad.png&h=160&w=160','logo',160,160,'#005A9C','#EF3E42','seed','unreviewed',NULL),
('team','chicago-cubs','Chicago Cubs','CHC','MLB','https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/chc.png&h=160&w=160','logo',160,160,'#0E3386','#CC3433','seed','unreviewed',NULL),
('team','philadelphia-phillies','Philadelphia Phillies','PHI','MLB','https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/phi.png&h=160&w=160','logo',160,160,'#E81828','#002D72','seed','unreviewed',NULL),
('team','new-york-giants','New York Giants','NYG','NFL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/nyg.png&h=160&w=160','logo',160,160,'#0B2265','#A71930','seed','unreviewed',NULL),
('team','new-york-jets','New York Jets','NYJ','NFL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/nyj.png&h=160&w=160','logo',160,160,'#125740','#FFFFFF','seed','unreviewed',NULL),
('team','philadelphia-eagles','Philadelphia Eagles','PHI','NFL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/phi.png&h=160&w=160','logo',160,160,'#004C54','#A5ACAF','seed','unreviewed',NULL),
('team','dallas-cowboys','Dallas Cowboys','DAL','NFL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/dal.png&h=160&w=160','logo',160,160,'#003594','#869397','seed','unreviewed',NULL),
('team','kansas-city-chiefs','Kansas City Chiefs','KC','NFL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/kc.png&h=160&w=160','logo',160,160,'#E31837','#FFB81C','seed','unreviewed',NULL),
('team','new-england-patriots','New England Patriots','NE','NFL','https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ne.png&h=160&w=160','logo',160,160,'#002244','#C60C30','seed','unreviewed',NULL),
('production','hamilton','Hamilton',NULL,NULL,NULL,NULL,NULL,NULL,'#111111','#B48A3C','seed','unreviewed',NULL),
('production','wicked','Wicked',NULL,NULL,NULL,NULL,NULL,NULL,'#0B3B2E','#7BC043','seed','unreviewed',NULL),
('production','the-lion-king','The Lion King',NULL,NULL,NULL,NULL,NULL,NULL,'#2B1A0E','#F2A900','seed','unreviewed',NULL),
('production','mj-the-musical','MJ The Musical',NULL,NULL,NULL,NULL,NULL,NULL,'#111111','#E5E5E5','seed','unreviewed',NULL),
('production','the-book-of-mormon','The Book of Mormon',NULL,NULL,NULL,NULL,NULL,NULL,'#1E3A8A','#F5D547','seed','unreviewed',NULL),
('production','hadestown','Hadestown',NULL,NULL,NULL,NULL,NULL,NULL,'#2A1A12','#C8862A','seed','unreviewed',NULL),
('production','chicago','Chicago',NULL,NULL,NULL,NULL,NULL,NULL,'#111111','#C8102E','seed','unreviewed',NULL),
('production','aladdin','Aladdin',NULL,NULL,NULL,NULL,NULL,NULL,'#2A2A72','#E8B923','seed','unreviewed',NULL),
('production','moulin-rouge-the-musical','Moulin Rouge! The Musical',NULL,NULL,NULL,NULL,NULL,NULL,'#5A0B12','#E31B23','seed','unreviewed',NULL),
('production','six','Six',NULL,NULL,NULL,NULL,NULL,NULL,'#1A1A1A','#C9A227','seed','unreviewed',NULL),
('category','concert','Concert',NULL,NULL,NULL,'artwork',1200,400,'#142438','#D7F36B','seed','licensed','Ticket Guy generated artwork'),
('category','sports','Sports',NULL,NULL,NULL,NULL,NULL,NULL,'#142438','#D7F36B','seed','licensed',NULL),
('category','theater','Theater',NULL,NULL,NULL,NULL,NULL,NULL,'#142438','#D7F36B','seed','licensed',NULL),
('category','comedy','Comedy',NULL,NULL,NULL,NULL,NULL,NULL,'#142438','#D7F36B','seed','licensed',NULL)
ON CONFLICT ("kind","key") DO NOTHING;
