import { TEAM_BRANDS, type TeamBrand } from '@/lib/brand/teams';

/**
 * What fans call a team, beyond its full name: the bare nickname ("Knicks"), the school ("Notre Dame"), the
 * abbreviations and the slang ("Bolts", "Habs", "Niners", "Sixers", "Bama"). Keyed by the roster slug
 * (src/lib/brand/teams/*.json, which build-team-brands rewrites, so these live here). A name more than one team
 * answers to ("Rangers", "Giants", "Tigers") is listed for each of them and is never read as one of them on its own:
 * the league they mention, or the question we ask, decides.
 */
const NICKNAMES: Record<string, string[]> = {
  // NFL
  'arizona-cardinals': ['Cardinals', 'Cards', 'Arizona Cardinals', 'Birdgang'],
  'atlanta-falcons': ['Falcons', 'Dirty Birds'],
  'baltimore-ravens': ['Ravens'],
  'buffalo-bills': ['Bills', 'Bills Mafia'],
  'carolina-panthers': ['Panthers'],
  'chicago-bears': ['Bears', 'Da Bears'],
  'cincinnati-bengals': ['Bengals', 'Bungles'],
  'cleveland-browns': ['Browns'],
  'dallas-cowboys': ['Cowboys', "America's Team"],
  'denver-broncos': ['Broncos'],
  'detroit-lions': ['Lions'],
  'green-bay-packers': ['Packers', 'Pack', 'Green Bay'],
  'houston-texans': ['Texans'],
  'indianapolis-colts': ['Colts', 'Indy Colts'],
  'jacksonville-jaguars': ['Jaguars', 'Jags'],
  'kansas-city-chiefs': ['Chiefs', 'KC Chiefs'],
  'las-vegas-raiders': ['Raiders', 'Silver and Black'],
  'los-angeles-chargers': ['Chargers', 'Bolts', 'LA Chargers'],
  'los-angeles-rams': ['Rams', 'LA Rams'],
  'miami-dolphins': ['Dolphins', 'Fins', 'Phins'],
  'minnesota-vikings': ['Vikings', 'Vikes'],
  'new-england-patriots': ['Patriots', 'Pats'],
  'new-orleans-saints': ['Saints', 'Who Dat'],
  'new-york-giants': ['Giants', 'G-Men', 'Big Blue', 'NY Giants', 'NYG'],
  'new-york-jets': ['Jets', 'Gang Green', 'NY Jets', 'NYJ'],
  'philadelphia-eagles': ['Eagles', 'Philly Eagles'],
  'pittsburgh-steelers': ['Steelers', 'Stillers'],
  'san-francisco-49ers': ['49ers', 'Niners', 'Forty Niners', 'SF 49ers'],
  'seattle-seahawks': ['Seahawks', 'Hawks'],
  'tampa-bay-buccaneers': ['Buccaneers', 'Bucs'],
  'tennessee-titans': ['Titans'],
  'washington-commanders': ['Commanders', 'Commies'],
  // NBA
  'atlanta-hawks': ['Hawks'],
  'boston-celtics': ['Celtics', 'Celts'],
  'brooklyn-nets': ['Nets', 'BK Nets'],
  'charlotte-hornets': ['Hornets', 'Buzz City'],
  'chicago-bulls': ['Bulls'],
  'cleveland-cavaliers': ['Cavaliers', 'Cavs'],
  'dallas-mavericks': ['Mavericks', 'Mavs'],
  'denver-nuggets': ['Nuggets', 'Nugs'],
  'detroit-pistons': ['Pistons', 'Stons'],
  'golden-state-warriors': ['Warriors', 'Dubs', 'Golden State', 'GSW'],
  'houston-rockets': ['Rockets'],
  'indiana-pacers': ['Pacers'],
  'la-clippers': ['Clippers', 'Clips', 'LA Clippers'],
  'los-angeles-lakers': ['Lakers', 'LA Lakers', 'Lake Show'],
  'memphis-grizzlies': ['Grizzlies', 'Grizz'],
  'miami-heat': ['Heat'],
  'milwaukee-bucks': ['Bucks'],
  'minnesota-timberwolves': ['Timberwolves', 'Wolves', 'T-Wolves', 'Twolves'],
  'new-orleans-pelicans': ['Pelicans', 'Pels'],
  'new-york-knicks': ['Knicks', 'Knickerbockers', 'NY Knicks', 'NYK'],
  'oklahoma-city-thunder': ['Thunder', 'OKC'],
  'orlando-magic': ['Magic'],
  'philadelphia-76ers': ['76ers', 'Sixers'],
  'phoenix-suns': ['Suns'],
  'portland-trail-blazers': ['Trail Blazers', 'Blazers', 'Rip City'],
  'sacramento-kings': ['Kings', 'Sac Kings'],
  'san-antonio-spurs': ['Spurs'],
  'toronto-raptors': ['Raptors', 'Raps'],
  'utah-jazz': ['Jazz'],
  'washington-wizards': ['Wizards', 'Wiz'],
  // WNBA
  'atlanta-dream': ['Dream'],
  'chicago-sky': ['Sky'],
  'connecticut-sun': ['Sun', 'CT Sun'],
  'dallas-wings': ['Wings'],
  'golden-state-valkyries': ['Valkyries', 'Valks'],
  'indiana-fever': ['Fever'],
  'las-vegas-aces': ['Aces'],
  'los-angeles-sparks': ['Sparks', 'LA Sparks'],
  'minnesota-lynx': ['Lynx'],
  'new-york-liberty': ['Liberty', 'NY Liberty', 'Libs'],
  'phoenix-mercury': ['Mercury', 'Merc'],
  'portland-fire': ['Fire'],
  'seattle-storm': ['Storm'],
  'toronto-tempo': ['Tempo'],
  'washington-mystics': ['Mystics'],
  // NHL
  'anaheim-ducks': ['Ducks'],
  'boston-bruins': ['Bruins', 'Spoked B'],
  'buffalo-sabres': ['Sabres'],
  'calgary-flames': ['Flames'],
  'carolina-hurricanes': ['Hurricanes', 'Canes', 'Carolina Canes'],
  'chicago-blackhawks': ['Blackhawks', 'Hawks'],
  'colorado-avalanche': ['Avalanche', 'Avs'],
  'columbus-blue-jackets': ['Blue Jackets', 'CBJ', 'Jackets'],
  'dallas-stars': ['Stars'],
  'detroit-red-wings': ['Red Wings', 'Wings'],
  'edmonton-oilers': ['Oilers'],
  'florida-panthers': ['Panthers', 'Cats', 'Florida Panthers'],
  'los-angeles-kings': ['Kings', 'LA Kings'],
  'minnesota-wild': ['Wild'],
  'montreal-canadiens': ['Canadiens', 'Habs', 'Les Habitants', 'Montreal Canadiens'],
  'nashville-predators': ['Predators', 'Preds'],
  'new-jersey-devils': ['Devils', 'NJ Devils'],
  'new-york-islanders': ['Islanders', 'Isles', 'NY Islanders', 'NYI'],
  'new-york-rangers': ['Rangers', 'Blueshirts', 'NY Rangers', 'NYR'],
  'ottawa-senators': ['Senators', 'Sens'],
  'philadelphia-flyers': ['Flyers', 'Broad Street Bullies'],
  'pittsburgh-penguins': ['Penguins', 'Pens'],
  'san-jose-sharks': ['Sharks'],
  'seattle-kraken': ['Kraken'],
  'st-louis-blues': ['Blues', 'St Louis Blues'],
  'tampa-bay-lightning': ['Lightning', 'Bolts', 'Tampa Lightning'],
  'toronto-maple-leafs': ['Maple Leafs', 'Leafs', 'Buds'],
  'utah-mammoth': ['Mammoth', 'Utah Hockey Club'],
  'vancouver-canucks': ['Canucks', 'Nucks'],
  'vegas-golden-knights': ['Golden Knights', 'Knights', 'VGK', 'Vegas Knights'],
  'washington-capitals': ['Capitals', 'Caps'],
  'winnipeg-jets': ['Jets', 'Winnipeg Jets'],
  // MLB
  'arizona-diamondbacks': ['Diamondbacks', 'Dbacks', 'D-backs', 'Snakes'],
  athletics: ['Athletics', "A's", 'Oakland Athletics', "Oakland A's"],
  'atlanta-braves': ['Braves'],
  'baltimore-orioles': ['Orioles', "O's"],
  'boston-red-sox': ['Red Sox', 'Sox', 'BoSox'],
  'chicago-cubs': ['Cubs', 'Cubbies', 'North Siders'],
  'chicago-white-sox': ['White Sox', 'ChiSox', 'Sox', 'South Siders'],
  'cincinnati-reds': ['Reds'],
  'cleveland-guardians': ['Guardians', 'Guards'],
  'colorado-rockies': ['Rockies'],
  'detroit-tigers': ['Tigers'],
  'houston-astros': ['Astros', 'Stros'],
  'kansas-city-royals': ['Royals'],
  'los-angeles-angels': ['Angels', 'Halos', 'Anaheim Angels'],
  'los-angeles-dodgers': ['Dodgers', 'Doyers', 'LA Dodgers'],
  'miami-marlins': ['Marlins', 'Fish'],
  'milwaukee-brewers': ['Brewers', 'Brew Crew'],
  'minnesota-twins': ['Twins'],
  'new-york-mets': ['Mets', 'Amazins', 'NY Mets', 'NYM'],
  'new-york-yankees': ['Yankees', 'Yanks', 'Bronx Bombers', 'NY Yankees', 'NYY'],
  'philadelphia-phillies': ['Phillies', 'Phils', 'Fightins'],
  'pittsburgh-pirates': ['Pirates', 'Bucs', 'Buccos'],
  'san-diego-padres': ['Padres', 'Friars', 'Pads'],
  'san-francisco-giants': ['Giants', 'SF Giants'],
  'seattle-mariners': ['Mariners', "M's"],
  'st-louis-cardinals': ['Cardinals', 'Cards', 'Redbirds', 'St Louis Cardinals'],
  'tampa-bay-rays': ['Rays'],
  'texas-rangers': ['Rangers', 'Texas Rangers'],
  'toronto-blue-jays': ['Blue Jays', 'Jays'],
  'washington-nationals': ['Nationals', 'Nats'],
  // MLS
  'atlanta-united-fc': ['Atlanta United', 'ATLUTD', 'Five Stripes'],
  'austin-fc': ['Austin FC', 'Verde'],
  'cf-montreal': ['CF Montreal', 'Montreal Impact'],
  'charlotte-fc': ['Charlotte FC'],
  'chicago-fire-fc': ['Chicago Fire'],
  'colorado-rapids': ['Rapids'],
  'columbus-crew': ['Crew', 'Columbus Crew'],
  'd-c-united': ['DC United', 'D.C. United'],
  'fc-cincinnati': ['FC Cincinnati', 'FCC'],
  'fc-dallas': ['FC Dallas'],
  'houston-dynamo-fc': ['Dynamo', 'Houston Dynamo'],
  'inter-miami-cf': ['Inter Miami', 'Inter Miami CF'],
  'la-galaxy': ['Galaxy', 'LA Galaxy'],
  lafc: ['LAFC', 'Los Angeles FC'],
  'minnesota-united-fc': ['Minnesota United', 'Loons'],
  'nashville-sc': ['Nashville SC'],
  'new-england-revolution': ['Revolution', 'Revs', 'New England Revolution'],
  'new-york-city-fc': ['NYCFC', 'NYC FC', 'New York City FC'],
  'orlando-city-sc': ['Orlando City', 'Lions'],
  'philadelphia-union': ['Union', 'Philadelphia Union'],
  'portland-timbers': ['Timbers'],
  'real-salt-lake': ['Real Salt Lake', 'RSL'],
  'red-bull-new-york': ['Red Bulls', 'New York Red Bulls', 'NY Red Bulls', 'RBNY'],
  'san-diego-fc': ['San Diego FC'],
  'san-jose-earthquakes': ['Earthquakes', 'Quakes'],
  'seattle-sounders-fc': ['Sounders', 'Seattle Sounders'],
  'sporting-kansas-city': ['Sporting KC', 'Sporting Kansas City', 'SKC'],
  'st-louis-city-sc': ['St Louis City', 'St. Louis City SC'],
  'toronto-fc': ['Toronto FC', 'TFC'],
  'vancouver-whitecaps': ['Whitecaps', 'Caps'],
  // NWSL
  'angel-city-fc': ['Angel City', 'Angel City FC'],
  'bay-fc': ['Bay FC'],
  'boston-legacy-fc': ['Boston Legacy'],
  'chicago-stars-fc': ['Chicago Stars', 'Chicago Red Stars'],
  'denver-summit-fc': ['Denver Summit'],
  'gotham-fc': ['Gotham', 'Gotham FC', 'NJ/NY Gotham FC'],
  'houston-dash': ['Dash', 'Houston Dash'],
  'kansas-city-current': ['KC Current', 'Kansas City Current'],
  'north-carolina-courage': ['Courage', 'NC Courage'],
  'orlando-pride': ['Pride', 'Orlando Pride'],
  'portland-thorns-fc': ['Thorns', 'Portland Thorns'],
  'racing-louisville-fc': ['Racing Louisville'],
  'san-diego-wave-fc': ['Wave', 'San Diego Wave'],
  'seattle-reign-fc': ['Reign', 'Seattle Reign'],
  'utah-royals': ['Utah Royals'],
  'washington-spirit': ['Spirit', 'Washington Spirit'],
  // NCAA: the school, its slang, and the mascot (shared mascots are never read alone)
  'alabama-crimson-tide': ['Alabama', 'Bama', 'Crimson Tide', 'Roll Tide'],
  'arizona-state-sun-devils': ['Arizona State', 'ASU', 'Sun Devils'],
  'arizona-wildcats': ['Arizona', 'Wildcats', 'U of A'],
  'arkansas-razorbacks': ['Arkansas', 'Razorbacks', 'Hogs'],
  'auburn-tigers': ['Auburn', 'Tigers', 'War Eagle'],
  'baylor-bears': ['Baylor', 'Bears'],
  'boston-college-eagles': ['Boston College', 'BC', 'Eagles'],
  'butler-bulldogs': ['Butler', 'Bulldogs'],
  'byu-cougars': ['BYU', 'Brigham Young', 'Cougars'],
  'california-golden-bears': ['Cal', 'California', 'Golden Bears', 'Berkeley'],
  'cincinnati-bearcats': ['Cincinnati', 'Bearcats', 'UC'],
  'clemson-tigers': ['Clemson', 'Tigers'],
  'colorado-buffaloes': ['Colorado', 'Buffaloes', 'Buffs', 'CU'],
  'creighton-bluejays': ['Creighton', 'Bluejays'],
  'depaul-blue-demons': ['DePaul', 'Blue Demons'],
  'duke-blue-devils': ['Duke', 'Blue Devils'],
  'florida-gators': ['Florida', 'Gators', 'UF'],
  'florida-state-seminoles': ['Florida State', 'FSU', 'Seminoles', 'Noles'],
  'georgetown-hoyas': ['Georgetown', 'Hoyas'],
  'georgia-bulldogs': ['Georgia', 'UGA', 'Bulldogs', 'Dawgs'],
  'georgia-tech-yellow-jackets': ['Georgia Tech', 'Yellow Jackets', 'GT'],
  'houston-cougars': ['Houston Cougars', 'Cougars', 'UH'],
  'illinois-fighting-illini': ['Illinois', 'Illini', 'Fighting Illini'],
  'indiana-hoosiers': ['Indiana', 'Hoosiers', 'IU'],
  'iowa-hawkeyes': ['Iowa', 'Hawkeyes', 'Hawks'],
  'iowa-state-cyclones': ['Iowa State', 'Cyclones', 'ISU'],
  'kansas-jayhawks': ['Kansas', 'Jayhawks', 'KU'],
  'kansas-state-wildcats': ['Kansas State', 'K-State', 'Wildcats', 'KSU'],
  'kentucky-wildcats': ['Kentucky', 'Wildcats', 'UK', 'Big Blue Nation', 'Cats'],
  'louisville-cardinals': ['Louisville', 'Cardinals', 'Cards', 'UofL'],
  'lsu-tigers': ['LSU', 'Louisiana State', 'Tigers', 'Bayou Bengals'],
  'marquette-golden-eagles': ['Marquette', 'Golden Eagles'],
  'maryland-terrapins': ['Maryland', 'Terrapins', 'Terps'],
  'miami-hurricanes': ['Miami Hurricanes', 'The U', 'Hurricanes', 'Canes', 'Miami (FL)'],
  'michigan-state-spartans': ['Michigan State', 'Spartans', 'MSU', 'Sparty'],
  'michigan-wolverines': ['Michigan', 'Wolverines', 'UM', 'Go Blue'],
  'minnesota-golden-gophers': ['Minnesota Gophers', 'Golden Gophers', 'Gophers'],
  'mississippi-state-bulldogs': ['Mississippi State', 'Miss State', 'Bulldogs'],
  'missouri-tigers': ['Missouri', 'Mizzou', 'Tigers'],
  'nc-state-wolfpack': ['NC State', 'North Carolina State', 'Wolfpack'],
  'nebraska-cornhuskers': ['Nebraska', 'Cornhuskers', 'Huskers'],
  'north-carolina-tar-heels': ['North Carolina', 'UNC', 'Tar Heels', 'Heels'],
  'northwestern-wildcats': ['Northwestern', 'Wildcats'],
  'notre-dame-fighting-irish': ['Notre Dame', 'Fighting Irish', 'Irish', 'ND'],
  'ohio-state-buckeyes': ['Ohio State', 'Buckeyes', 'OSU', 'tOSU'],
  'oklahoma-sooners': ['Oklahoma', 'Sooners', 'OU'],
  'oklahoma-state-cowboys': ['Oklahoma State', 'OK State', 'Okie State', 'Cowboys', 'Pokes'],
  'ole-miss-rebels': ['Ole Miss', 'Mississippi', 'Rebels'],
  'oregon-ducks': ['Oregon', 'Ducks', 'UO'],
  'penn-state-nittany-lions': ['Penn State', 'Nittany Lions', 'PSU'],
  'pittsburgh-panthers': ['Pitt', 'Pittsburgh Panthers', 'Panthers'],
  'providence-friars': ['Providence', 'Friars'],
  'purdue-boilermakers': ['Purdue', 'Boilermakers', 'Boilers'],
  'rutgers-scarlet-knights': ['Rutgers', 'Scarlet Knights', 'RU'],
  'seton-hall-pirates': ['Seton Hall', 'Pirates', 'The Hall'],
  'smu-mustangs': ['SMU', 'Southern Methodist', 'Mustangs', 'Ponies'],
  'south-carolina-gamecocks': ['South Carolina', 'Gamecocks', 'USC Gamecocks'],
  'st-john-s-red-storm': ["St. John's", 'St Johns', 'Red Storm', 'Johnnies'],
  'stanford-cardinal': ['Stanford', 'Cardinal', 'The Farm'],
  'syracuse-orange': ['Syracuse', 'Orange', 'Cuse', "'Cuse"],
  'tcu-horned-frogs': ['TCU', 'Texas Christian', 'Horned Frogs', 'Frogs'],
  'tennessee-volunteers': ['Tennessee', 'Volunteers', 'Vols', 'UT Vols'],
  'texas-a-m-aggies': ['Texas A&M', 'Texas AM', 'A&M', 'Aggies', 'TAMU'],
  'texas-longhorns': ['Texas', 'Longhorns', 'Horns', 'UT Austin'],
  'texas-tech-red-raiders': ['Texas Tech', 'Red Raiders', 'TTU'],
  'ucf-knights': ['UCF', 'Central Florida', 'Knights'],
  'ucla-bruins': ['UCLA', 'Bruins'],
  'uconn-huskies': ['UConn', 'Connecticut', 'Huskies'],
  'usc-trojans': ['USC', 'Southern Cal', 'Trojans', 'SC'],
  'utah-utes': ['Utah Utes', 'Utes'],
  'vanderbilt-commodores': ['Vanderbilt', 'Vandy', 'Commodores', 'Dores'],
  'villanova-wildcats': ['Villanova', 'Nova', 'Wildcats'],
  'virginia-cavaliers': ['Virginia', 'UVA', 'Cavaliers', 'Wahoos', 'Hoos'],
  'virginia-tech-hokies': ['Virginia Tech', 'Hokies', 'VT'],
  'wake-forest-demon-deacons': ['Wake Forest', 'Wake', 'Demon Deacons', 'Deacs'],
  'washington-huskies': ['Washington Huskies', 'UW', 'Huskies', 'Dawgs'],
  'west-virginia-mountaineers': ['West Virginia', 'WVU', 'Mountaineers', 'Eers'],
  'wisconsin-badgers': ['Wisconsin', 'Badgers', 'Bucky'],
  'xavier-musketeers': ['Xavier', 'Musketeers'],
};

const norm = (s: string) => s.toLowerCase().replace(/[’']/g, '').replace(/[^a-z0-9&]+/g, ' ').trim();

/** Every name a roster team answers to: its full name, its short code, its provider slugs and the nicknames above. */
export function teamNames(t: TeamBrand): string[] {
  return [...new Set([t.name, ...(t.shortName && t.shortName.length >= 3 ? [t.shortName] : []), ...t.aliases.map((a) => a.replace(/-/g, ' ')), ...(NICKNAMES[t.slug] ?? [])])];
}

/** The roster as the name matchers take it: the full name, and every other name as an alias. */
export const ROSTER_NAMES: ReadonlyArray<{ name: string; aliases: string[]; league: TeamBrand['league'] }> = TEAM_BRANDS.map((t) => ({ name: t.name, aliases: teamNames(t).filter((n) => n !== t.name), league: t.league }));

const LEAGUE_HINT: Record<string, TeamBrand['league'][]> = {
  nfl: ['NFL'], nba: ['NBA'], wnba: ['WNBA'], nhl: ['NHL'], mlb: ['MLB'], soccer: ['MLS', 'NWSL'], mls: ['MLS'], nwsl: ['NWSL'], ncaaf: ['NCAA'], ncaab: ['NCAA'],
};

/**
 * The one roster team a name means: "Bolts" is the Tampa Bay Lightning, "Bama" is Alabama. A name several teams
 * answer to ("Rangers", "Tigers") is narrowed by the league they named, and is otherwise nobody in particular (null),
 * so the reply can ask instead of guessing.
 */
export function rosterTeam(typed: string | null | undefined, categoryHint?: string | null): string | null {
  const n = norm(typed ?? '');
  if (!n) return null;
  const leagues = categoryHint ? LEAGUE_HINT[categoryHint] : undefined;
  const hits = TEAM_BRANDS.filter((t) => teamNames(t).some((x) => norm(x) === n) && (!leagues || leagues.includes(t.league)));
  return hits.length === 1 ? hits[0]!.name : null;
}
